[返回主页面](../README.md)

[上一条](20230330.md)

- 学习 Rust 的错误处理部分。文档章节《Rust 语言圣经》[2.11 返回值和错误处理](https://course.rs/basic/result-error/intro.html)或者《Rust 程序设计语言》[9.错误处理](https://kaisery.github.io/trpl-zh-cn/ch09-00-error-handling.html)

- 完成了 [rustlings](https://github.com/LearningOS/rust-rustlings-creatoy) 中错误处理相关练习。

Rust 的错误处理具有自己的特色。主要使用 panic!（不可恢复错误） 和 Result （可恢复错误）进行处理。

panic! 使程序直接结束并输出崩溃信息，可以在遇到程序无法自己进行处理的错误或者不能继续正常运行时（如系统异常或者无法获取到后续运行需要的资源等情况）使用。

Result<T, E> 是一个泛型的枚举类型，函数正常处理时可解构出结果，处理失败时可解构出错误信息。Result 的 unwrap 方法可以简单粗暴的解包 Ok 的结果，但是当其是 Err 时也简单粗暴地 panic 了。如果能确定得到的 Result 一定是 Ok，那就能愉快地用 unwrap。类似的还有 expect 方法，区别只是你可以自定义 panic 的信息。

Result<T, E> 和 Option<T> 很相似，只不过 Option<T> 是用于有没有值的包装（None 的情况不会包含额外的数据），Result<T, E> 是对函数执行情况的包装（Ok(T) 成功时的结果/Err(E) 失败时的错误信息）。

有时候我们只想在本函数内完成正常的功能，不想直接处理错误，而是将错误时的情况传递给更上层的函数。这时就可以在匹配到 Err 的时候给它 return 出去（这个函数的返回值类型也得是个 Result 类型）。不过 Rust 给我们提供了一个更方便的符号 `?`，`？` 就相当于一次对 Result 或 Option 的模式匹配，当结果是 Ok / Some 时`解构出其中的值`，当结果是 Err / None 时，会将其返回出去。
如下面的函数，当 open 和 read_to_string 都获得了正常的结果时会运行到最后返回 Ok(s)，如果前面出现 Err 就会直接将错误返回。
```rust
use std::fs;
use std::fs::File;
use std::io;
use std::io::Read;

fn read_username_from_file() -> Result<String, io::Error> {
    let mut f = File::open("hello.txt")?;
    let mut s = String::new();
    f.read_to_string(&mut s)?;
	// 上面两行也可以直接像这样进行链式调用，效果相同
	// File::open("hello.txt")?.read_to_string(&mut s)?;
    Ok(s)
	// 或者上面几行用下面这行标准库的函数直接完成
	// fs::read_to_string("hello.txt")
}
```

> 注意 `?` 匹配出 Ok 或 Some 是直接解构出其中的值的，所以这个值是不能作为返回 Resut / Option 类型的函数的返回值的，而是要再包装一下才行。如下面的这个函数就会报错
> ```rust
> fn first(arr: &[i32]) -> Option<&i32> {
>     arr.get(0)?
>     // 需要写成下面这样才行
>     // let v = arr.get(0)?;
>     // Some(v)
> }
> ```